"""added_image_column_to_books

Revision ID: 0a7616eb63f2
Revises: 51aeab519632
Create Date: 2023-11-12 22:44:00.937035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7616eb63f2'
down_revision: Union[str, None] = '51aeab519632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'img')
    # ### end Alembic commands ###
