"""message of what table was updated

Revision ID: 0abaacebb9ab
Revises: aa9994e70523
Create Date: 2023-11-18 12:28:28.900367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abaacebb9ab'
down_revision: Union[str, None] = 'aa9994e70523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('item_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'item_id')
    # ### end Alembic commands ###
