"""updated_accessories_books

Revision ID: 4082629ad6ab
Revises: bbef3f7dd096
Create Date: 2023-11-15 05:25:17.270906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4082629ad6ab'
down_revision: Union[str, None] = 'bbef3f7dd096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
