"""added_column_to_accessories

Revision ID: 71bc2d06c17b
Revises: c77d9e89a339
Create Date: 2023-11-19 20:08:35.198660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bc2d06c17b'
down_revision: Union[str, None] = 'c77d9e89a339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessories', sa.Column('display_on_homepage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accessories', 'display_on_homepage')
    # ### end Alembic commands ###
