"""added_img_to_accessories

Revision ID: 8641e528bd86
Revises: 4082629ad6ab
Create Date: 2023-11-15 05:36:20.569250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8641e528bd86'
down_revision: Union[str, None] = '4082629ad6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessories', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accessories', 'img')
    # ### end Alembic commands ###
