"""message of what table was updated

Revision ID: 904c2f059c49
Revises: 5db2503b7137
Create Date: 2023-11-17 23:07:32.257623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904c2f059c49'
down_revision: Union[str, None] = '5db2503b7137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'session_id',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'session_id',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
