"""message of what table was updated

Revision ID: a7b6c080681d
Revises: 0abaacebb9ab
Create Date: 2023-11-18 18:32:50.263943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b6c080681d'
down_revision: Union[str, None] = '0abaacebb9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('availability', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'availability')
    # ### end Alembic commands ###
