"""initial

Revision ID: b29d82bde3b8
Revises: 
Create Date: 2023-11-01 19:28:33.981309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migrations.test_data.populate_initial import Populate


# revision identifiers, used by Alembic.
revision: str = 'b29d82bde3b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    pop = Populate()
    pop.insert_user_accounts()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
