"""doing more table stuff

Revision ID: c547b5ca882e
Revises: 0a7616eb63f2
Create Date: 2023-11-14 16:47:32.899359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c547b5ca882e'
down_revision: Union[str, None] = '0a7616eb63f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessories',
    sa.Column('accessory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('accessory_id')
    )
    op.create_table('administrators',
    sa.Column('accessory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('accessory_id')
    )
    op.create_table('customer_with_accounts',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('username', 'password', 'email', 'phone_number')
    )
    op.create_table('customer_without_accounts',
    sa.Column('guest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guest_id')
    )
    op.create_table('accessory_orders',
    sa.Column('accessory_order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accessory_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_total', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.accessory_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_with_accounts.customer_id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['customer_without_accounts.guest_id'], ),
    sa.PrimaryKeyConstraint('accessory_order_id')
    )
    op.create_table('book_and_accessory_orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('accessory_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Text(), nullable=True),
    sa.Column('order_total', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.accessory_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_with_accounts.customer_id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['customer_without_accounts.guest_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('book_orders',
    sa.Column('book_order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_total', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_with_accounts.customer_id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['customer_without_accounts.guest_id'], ),
    sa.PrimaryKeyConstraint('book_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_orders')
    op.drop_table('book_and_accessory_orders')
    op.drop_table('accessory_orders')
    op.drop_table('customer_without_accounts')
    op.drop_table('customer_with_accounts')
    op.drop_table('administrators')
    op.drop_table('accessories')
    # ### end Alembic commands ###
