"""added_column_to_books

Revision ID: c77d9e89a339
Revises: d9640de2c433
Create Date: 2023-11-19 18:53:59.458032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77d9e89a339'
down_revision: Union[str, None] = 'd9640de2c433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('display_on_homepage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'display_on_homepage')
    # ### end Alembic commands ###
