"""revisions

Revision ID: cc6c6499cec2
Revises: c547b5ca882e
Create Date: 2023-11-14 19:27:40.160736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6c6499cec2'
down_revision: Union[str, None] = 'c547b5ca882e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('username', 'password', 'email', 'phone_number')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('accessory_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Text(), nullable=True),
    sa.Column('order_total', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.accessory_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.drop_table('customer_without_accounts')
    op.drop_table('book_orders')
    op.drop_table('administrators')
    op.drop_table('customer_with_accounts')
    op.drop_table('accessory_orders')
    op.drop_table('user_accounts')
    op.drop_table('book_and_accessory_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_and_accessory_orders',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('accessory_id', sa.INTEGER(), nullable=True),
    sa.Column('guest_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('order_date', sa.TEXT(), nullable=True),
    sa.Column('order_total', sa.DOUBLE(), nullable=True),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.accessory_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_with_accounts.customer_id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['customer_without_accounts.guest_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('user_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstName', sa.VARCHAR(), nullable=True),
    sa.Column('lastName', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accessory_orders',
    sa.Column('accessory_order_id', sa.INTEGER(), nullable=False),
    sa.Column('accessory_id', sa.INTEGER(), nullable=True),
    sa.Column('guest_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('order_total', sa.DOUBLE(), nullable=True),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.accessory_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_with_accounts.customer_id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['customer_without_accounts.guest_id'], ),
    sa.PrimaryKeyConstraint('accessory_order_id')
    )
    op.create_table('customer_with_accounts',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('username', 'password', 'email', 'phone_number')
    )
    op.create_table('administrators',
    sa.Column('accessory_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('accessory_id')
    )
    op.create_table('book_orders',
    sa.Column('book_order_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('guest_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('order_total', sa.DOUBLE(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_with_accounts.customer_id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['customer_without_accounts.guest_id'], ),
    sa.PrimaryKeyConstraint('book_order_id')
    )
    op.create_table('customer_without_accounts',
    sa.Column('guest_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('guest_id')
    )
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
