"""message of what table was updated

Revision ID: e3e02d4cd507
Revises: d9640de2c433
Create Date: 2023-11-19 22:36:11.985816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e02d4cd507'
down_revision: Union[str, None] = 'd9640de2c433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', sa.INTEGER(), nullable=False))
    op.drop_column('orders', 'username')
    # ### end Alembic commands ###
